services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn special_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: special_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
